export const SERIF_FONTS = [
  'Abhaya Libre',
  'Abyssinica SIL',
  'Adamina',
  'Alegreya',
  'Alegreya SC',
  'Aleo',
  'Alice',
  'Alike',
  'Alike Angular',
  'Alkalami',
  'Almendra',
  'Almendra SC',
  'Amethysta',
  'Amiri',
  'Amiri Quran',
  'Andada Pro',
  'Antic Didone',
  'Antic Slab',
  'Aoboshi One',
  'Arapey',
  'Arbutus',
  'Arbutus Slab',
  'Aref Ruqaa',
  'Aref Ruqaa Ink',
  'Artifika',
  'Arvo',
  'Asar',
  'Average',
  'BIZ UDMincho',
  'BIZ UDPMincho',
  'Bacasime Antique',
  'Balthazar',
  'Baskervville',
  'Belgrano',
  'Bellefair',
  'Benne',
  'Bentham',
  'Besley',
  'Bevan',
  'BhuTuka Expanded One',
  'BioRhyme',
  'BioRhyme Expanded',
  'Bitter',
  'Bodoni Moda',
  'Bona Nova',
  'Brawler',
  'Bree Serif',
  'Brygada 1918',
  'Buenard',
  'Caladea',
  'Cambo',
  'Cantata One',
  'Cardo',
  'Castoro',
  'Caudex',
  'Charis SIL',
  'Cinzel',
  'Copse',
  'Cormorant',
  'Cormorant Garamond',
  'Cormorant Infant',
  'Cormorant SC',
  'Cormorant Unicase',
  'Cormorant Upright',
  'Coustard',
  'Crete Round',
  'Crimson Pro',
  'Crimson Text',
  'Cutive',
  'DM Serif Display',
  'DM Serif Text',
  'Dai Banna SIL',
  'David Libre',
  'Della Respira',
  'Diphylleia',
  'Domine',
  'Donegal One',
  'EB Garamond',
  'Eczar',
  'Enriqueta',
  'Esteban',
  'Fanwood Text',
  'Fauna One',
  'Faustina',
  'Fenix',
  'Fjord One',
  'Frank Ruhl Libre',
  'Fraunces',
  'GFS Didot',
  'Gabriela',
  'Gelasio',
  'Gentium Book Plus',
  'Gentium Plus',
  'Gilda Display',
  'Glegoo',
  'Gloock',
  'Goudy Bookletter 1911',
  'Gowun Batang',
  'Graduate',
  'Grandiflora One',
  'Grenze',
  'Gulzar',
  'Gupter',
  'Gurajada',
  'Habibi',
  'Hahmlet',
  'Halant',
  'Hanuman',
  'Headland One',
  'Hedvig Letters Serif',
  'Hepta Slab',
  'Hina Mincho',
  'Holtwood One SC',
  'IBM Plex Serif',
  'IM Fell DW Pica',
  'IM Fell DW Pica SC',
  'IM Fell Double Pica',
  'IM Fell Double Pica SC',
  'IM Fell English',
  'IM Fell English SC',
  'IM Fell French Canon',
  'IM Fell French Canon SC',
  'IM Fell Great Primer',
  'IM Fell Great Primer SC',
  'Ibarra Real Nova',
  'Imbue',
  'Inika',
  'Inknut Antiqua',
  'Inria Serif',
  'Instrument Serif',
  'Italiana',
  'Jacques Francois',
  'Joan',
  'Jomolhari',
  'Josefin Slab',
  'Judson',
  'Junge',
  'Kadwa',
  'Kaisei Decol',
  'Kaisei HarunoUmi',
  'Kaisei Opti',
  'Kaisei Tokumin',
  'Kalnia',
  'Kameron',
  'Karma',
  'Kay Pho Du',
  'Kiwi Maru',
  'Koh Santepheap',
  'Kotta One',
  'Kreon',
  'Kurale',
  'Labrada',
  'Lateef',
  'Ledger',
  'Libre Baskerville',
  'Libre Bodoni',
  'Libre Caslon Display',
  'Libre Caslon Text',
  'Linden Hill',
  'Lisu Bosa',
  'Literata',
  'Lora',
  'Lusitana',
  'Lustria',
  'Maiden Orange',
  'Maitree',
  'Manuale',
  'Marcellus',
  'Marcellus SC',
  'Markazi Text',
  'Marko One',
  'Martel',
  'Mate',
  'Mate SC',
  'Merriweather',
  'Mirza',
  'Montaga',
  'Montagu Slab',
  'Nanum Myeongjo',
  'Narnoor',
  'Neuton',
  'New Tegomin',
  'Newsreader',
  'Noticia Text',
  'Noto Naskh Arabic',
  'Noto Nastaliq Urdu',
  'Noto Rashi Hebrew',
  'Noto Serif',
  'Noto Serif Ahom',
  'Noto Serif Armenian',
  'Noto Serif Balinese',
  'Noto Serif Bengali',
  'Noto Serif Devanagari',
  'Noto Serif Display',
  'Noto Serif Dogra',
  'Noto Serif Ethiopic',
  'Noto Serif Georgian',
  'Noto Serif Grantha',
  'Noto Serif Gujarati',
  'Noto Serif Gurmukhi',
  'Noto Serif HK',
  'Noto Serif Hebrew',
  'Noto Serif JP',
  'Noto Serif KR',
  'Noto Serif Kannada',
  'Noto Serif Khitan Small Script',
  'Noto Serif Khmer',
  'Noto Serif Khojki',
  'Noto Serif Lao',
  'Noto Serif Makasar',
  'Noto Serif Malayalam',
  'Noto Serif Myanmar',
  'Noto Serif NP Hmong',
  'Noto Serif Old Uyghur',
  'Noto Serif Oriya',
  'Noto Serif Ottoman Siyaq',
  'Noto Serif SC',
  'Noto Serif Sinhala',
  'Noto Serif TC',
  'Noto Serif Tamil',
  'Noto Serif Tangut',
  'Noto Serif Telugu',
  'Noto Serif Thai',
  'Noto Serif Tibetan',
  'Noto Serif Toto',
  'Noto Serif Vithkuqi',
  'Noto Serif Yezidi',
  'Odor Mean Chey',
  'Old Standard TT',
  'Oranienbaum',
  'Ovo',
  'PT Serif',
  'PT Serif Caption',
  'Padyakke Expanded One',
  'Peddana',
  'Peralta',
  'Petrona',
  'Piazzolla',
  'Playfair',
  'Playfair Display',
  'Playfair Display SC',
  'Podkova',
  'Poltawski Nowy',
  'Poly',
  'Port Lligat Slab',
  'Prata',
  'Pridi',
  'Prociono',
  'Quando',
  'Quattrocento',
  'Radley',
  'Ramaraja',
  'Rasa',
  'Rhodium Libre',
  'Roboto Serif',
  'Roboto Slab',
  'Rokkitt',
  'Rosarivo',
  'Rozha One',
  'Rufina',
  'Ruwudu',
  'STIX Two Text',
  'Sahitya',
  'Sanchez',
  'Sawarabi Mincho',
  'Scheherazade New',
  'Scope One',
  'Shippori Mincho',
  'Shippori Mincho B1',
  'Slabo 13px',
  'Slabo 27px',
  'Solway',
  'Song Myung',
  'Sorts Mill Goudy',
  'Source Serif 4',
  'Spectral',
  'Spectral SC',
  'Sree Krushnadevaraya',
  'Stint Ultra Condensed',
  'Stint Ultra Expanded',
  'Stoke',
  'Suez One',
  'Sumana',
  'Sura',
  'Suranna',
  'Suravaram',
  'Suwannaphum',
  'Tai Heritage Pro',
  'Taviraj',
  'Texturina',
  'Tienne',
  'Tinos',
  'Tiro Bangla',
  'Tiro Devanagari Hindi',
  'Tiro Devanagari Marathi',
  'Tiro Devanagari Sanskrit',
  'Tiro Gurmukhi',
  'Tiro Kannada',
  'Tiro Tamil',
  'Tiro Telugu',
  'Trirong',
  'Trocchi',
  'Trykker',
  'Uchen',
  'Ultra',
  'Unna',
  'Vast Shadow',
  'Vesper Libre',
  'Vidaloka',
  'Volkhov',
  'Vollkorn',
  'Vollkorn SC',
  'Wellfleet',
  'Young Serif',
  'Yrsa',
  'Yuji Boku',
  'Yuji Mai',
  'Yuji Syuku',
  'Zen Antique',
  'Zen Antique Soft',
  'Zen Old Mincho',
  'Zilla Slab',
  'Zilla Slab Highlight',
]

export const MONO_FONTS = [
  'Anonymous Pro',
  'Azeret Mono',
  'B612 Mono',
  'Chivo Mono',
  'Courier Prime',
  'Cousine',
  'Cutive Mono',
  'DM Mono',
  'Fira Code',
  'Fira Mono',
  'Fragment Mono',
  'IBM Plex Mono',
  'Inconsolata',
  'JetBrains Mono',
  'M PLUS 1 Code',
  'Major Mono Display',
  'Martian Mono',
  'Material Icons',
  'Material Icons Outlined',
  'Material Icons Round',
  'Material Icons Sharp',
  'Material Icons Two Tone',
  'Material Symbols Outlined',
  'Material Symbols Rounded',
  'Material Symbols Sharp',
  'Monofett',
  'Nova Mono',
  'Overpass Mono',
  'Oxygen Mono',
  'PT Mono',
  'Red Hat Mono',
  'Roboto Mono',
  'Share Tech Mono',
  'Sometype Mono',
  'Source Code Pro',
  'Space Mono',
  'Spline Sans Mono',
  'Syne Mono',
  'Ubuntu Mono',
  'VT323',
  'Victor Mono',
  'Xanh Mono',
]

export const SANS_FONTS = [
  'ABeeZee',
  'AR One Sans',
  'Abel',
  'Aclonica',
  'Acme',
  'Actor',
  'Advent Pro',
  'Afacad',
  'Agdasima',
  'Akatab',
  'Akshar',
  'Alata',
  'Alatsi',
  'Albert Sans',
  'Aldrich',
  'Alef',
  'Alegreya Sans',
  'Alegreya Sans SC',
  'Alexandria',
  'Allerta',
  'Allerta Stencil',
  'Almarai',
  'Alumni Sans',
  'Alumni Sans Collegiate One',
  'Alumni Sans Pinstripe',
  'Amaranth',
  'Amiko',
  'Anaheim',
  'Andika',
  'Anek Bangla',
  'Anek Devanagari',
  'Anek Gujarati',
  'Anek Gurmukhi',
  'Anek Kannada',
  'Anek Latin',
  'Anek Malayalam',
  'Anek Odia',
  'Anek Tamil',
  'Anek Telugu',
  'Antic',
  'Anton',
  'Antonio',
  'Anuphan',
  'Archivo',
  'Archivo Black',
  'Archivo Narrow',
  'Arimo',
  'Armata',
  'Arsenal',
  'Arya',
  'Asap',
  'Asap Condensed',
  'Assistant',
  'Asul',
  'Athiti',
  'Atkinson Hyperlegible',
  'Average Sans',
  'B612',
  'BIZ UDGothic',
  'BIZ UDPGothic',
  'Bai Jamjuree',
  'Barlow',
  'Barlow Condensed',
  'Barlow Semi Condensed',
  'Basic',
  'Bayon',
  'Be Vietnam Pro',
  'Bebas Neue',
  'Belanosima',
  'Belleza',
  'BenchNine',
  'Biryani',
  'Black Han Sans',
  'Blinker',
  'Braah One',
  'Bricolage Grotesque',
  'Bubbler One',
  'Cabin',
  'Cabin Condensed',
  'Cagliostro',
  'Cairo',
  'Cairo Play',
  'Cambay',
  'Candal',
  'Cantarell',
  'Cantora One',
  'Capriola',
  'Carlito',
  'Carme',
  'Carrois Gothic',
  'Carrois Gothic SC',
  'Catamaran',
  'Chakra Petch',
  'Changa',
  'Chathura',
  'Chau Philomene One',
  'Chivo',
  'Comme',
  'Commissioner',
  'Convergence',
  'Cuprum',
  'DM Sans',
  'Darker Grotesque',
  'Days One',
  'Denk One',
  'Dhurjati',
  'Didact Gothic',
  'Do Hyeon',
  'Dongle',
  'Doppio One',
  'Dorsa',
  'Dosis',
  'DotGothic16',
  'Duru Sans',
  'Economica',
  'El Messiri',
  'Electrolize',
  'Encode Sans',
  'Encode Sans Condensed',
  'Encode Sans Expanded',
  'Encode Sans SC',
  'Encode Sans Semi Condensed',
  'Encode Sans Semi Expanded',
  'Englebert',
  'Epilogue',
  'Exo',
  'Exo 2',
  'Fahkwang',
  'Familjen Grotesk',
  'Farro',
  'Federo',
  'Figtree',
  'Finlandica',
  'Fira Sans',
  'Fira Sans Condensed',
  'Fira Sans Extra Condensed',
  'Fjalla One',
  'Francois One',
  'Fredoka',
  'Fresca',
  'GFS Neohellenic',
  'Gafata',
  'Galdeano',
  'Gantari',
  'Gasoek One',
  'Gayathri',
  'Gemunu Libre',
  'Genos',
  'Geo',
  'Geologica',
  'Georama',
  'Gidugu',
  'Glory',
  'Golos Text',
  'Gothic A1',
  'Gotu',
  'Gowun Dodum',
  'Gruppo',
  'Gudea',
  'Hammersmith One',
  'Hanken Grotesk',
  'Harmattan',
  'Hedvig Letters Sans',
  'Heebo',
  'Hind',
  'Hind Guntur',
  'Hind Madurai',
  'Hind Siliguri',
  'Hind Vadodara',
  'Homenaje',
  'Hubballi',
  'IBM Plex Sans',
  'IBM Plex Sans Arabic',
  'IBM Plex Sans Condensed',
  'IBM Plex Sans Devanagari',
  'IBM Plex Sans Hebrew',
  'IBM Plex Sans JP',
  'IBM Plex Sans KR',
  'IBM Plex Sans Thai',
  'IBM Plex Sans Thai Looped',
  'Imprima',
  'Inclusive Sans',
  'Inder',
  'Inria Sans',
  'Instrument Sans',
  'Inter',
  'Inter Tight',
  'Istok Web',
  'Jaldi',
  'Jockey One',
  'Josefin Sans',
  'Jost',
  'Jua',
  'Julius Sans One',
  'Jura',
  'K2D',
  'Kanit',
  'Kantumruy Pro',
  'Karla',
  'Kdam Thmor Pro',
  'Khand',
  'Khmer',
  'Khula',
  'Kite One',
  'KoHo',
  'Kodchasan',
  'Kosugi',
  'Kosugi Maru',
  'Krona One',
  'Krub',
  'Kufam',
  'Kulim Park',
  'Kumbh Sans',
  'Laila',
  'Lato',
  'League Gothic',
  'League Spartan',
  'Lekton',
  'Lexend',
  'Lexend Deca',
  'Lexend Exa',
  'Lexend Giga',
  'Lexend Mega',
  'Lexend Peta',
  'Lexend Tera',
  'Lexend Zetta',
  'Libre Franklin',
  'Livvic',
  'Lunasima',
  'M PLUS 1',
  'M PLUS 1p',
  'M PLUS 2',
  'M PLUS Code Latin',
  'M PLUS Rounded 1c',
  'Mada',
  'Magra',
  'Mako',
  'Mallanna',
  'Mandali',
  'Manjari',
  'Manrope',
  'Marmelad',
  'Martel Sans',
  'Marvel',
  'Maven Pro',
  'Meera Inimai',
  'Merriweather Sans',
  'Metrophobic',
  'Michroma',
  'Mina',
  'Mingzat',
  'Miriam Libre',
  'Mitr',
  'Mochiy Pop One',
  'Mochiy Pop P One',
  'Mohave',
  'Molengo',
  'Monda',
  'Monomaniac One',
  'Montserrat',
  'Montserrat Alternates',
  'Montserrat Subrayada',
  'Mooli',
  'Moulpali',
  'Mouse Memoirs',
  'Mukta',
  'Mukta Mahee',
  'Mukta Malar',
  'Mukta Vaani',
  'Mulish',
  'Murecho',
  'NTR',
  'Nanum Gothic',
  'News Cycle',
  'Niramit',
  'Nobile',
  'Nokora',
  'Notable',
  'Noto Color Emoji',
  'Noto Emoji',
  'Noto Kufi Arabic',
  'Noto Music',
  'Noto Sans',
  'Noto Sans Adlam',
  'Noto Sans Adlam Unjoined',
  'Noto Sans Anatolian Hieroglyphs',
  'Noto Sans Arabic',
  'Noto Sans Armenian',
  'Noto Sans Avestan',
  'Noto Sans Balinese',
  'Noto Sans Bamum',
  'Noto Sans Bassa Vah',
  'Noto Sans Batak',
  'Noto Sans Bengali',
  'Noto Sans Bhaiksuki',
  'Noto Sans Brahmi',
  'Noto Sans Buginese',
  'Noto Sans Buhid',
  'Noto Sans Canadian Aboriginal',
  'Noto Sans Carian',
  'Noto Sans Caucasian Albanian',
  'Noto Sans Chakma',
  'Noto Sans Cham',
  'Noto Sans Cherokee',
  'Noto Sans Chorasmian',
  'Noto Sans Coptic',
  'Noto Sans Cuneiform',
  'Noto Sans Cypriot',
  'Noto Sans Cypro Minoan',
  'Noto Sans Deseret',
  'Noto Sans Devanagari',
  'Noto Sans Display',
  'Noto Sans Duployan',
  'Noto Sans Egyptian Hieroglyphs',
  'Noto Sans Elbasan',
  'Noto Sans Elymaic',
  'Noto Sans Ethiopic',
  'Noto Sans Georgian',
  'Noto Sans Glagolitic',
  'Noto Sans Gothic',
  'Noto Sans Grantha',
  'Noto Sans Gujarati',
  'Noto Sans Gunjala Gondi',
  'Noto Sans Gurmukhi',
  'Noto Sans HK',
  'Noto Sans Hanifi Rohingya',
  'Noto Sans Hanunoo',
  'Noto Sans Hatran',
  'Noto Sans Hebrew',
  'Noto Sans Imperial Aramaic',
  'Noto Sans Indic Siyaq Numbers',
  'Noto Sans Inscriptional Pahlavi',
  'Noto Sans Inscriptional Parthian',
  'Noto Sans JP',
  'Noto Sans Javanese',
  'Noto Sans KR',
  'Noto Sans Kaithi',
  'Noto Sans Kannada',
  'Noto Sans Kawi',
  'Noto Sans Kayah Li',
  'Noto Sans Kharoshthi',
  'Noto Sans Khmer',
  'Noto Sans Khojki',
  'Noto Sans Khudawadi',
  'Noto Sans Lao',
  'Noto Sans Lao Looped',
  'Noto Sans Lepcha',
  'Noto Sans Limbu',
  'Noto Sans Linear A',
  'Noto Sans Linear B',
  'Noto Sans Lisu',
  'Noto Sans Lycian',
  'Noto Sans Lydian',
  'Noto Sans Mahajani',
  'Noto Sans Malayalam',
  'Noto Sans Mandaic',
  'Noto Sans Manichaean',
  'Noto Sans Marchen',
  'Noto Sans Masaram Gondi',
  'Noto Sans Math',
  'Noto Sans Mayan Numerals',
  'Noto Sans Medefaidrin',
  'Noto Sans Meetei Mayek',
  'Noto Sans Mende Kikakui',
  'Noto Sans Meroitic',
  'Noto Sans Miao',
  'Noto Sans Modi',
  'Noto Sans Mongolian',
  'Noto Sans Mono',
  'Noto Sans Mro',
  'Noto Sans Multani',
  'Noto Sans Myanmar',
  'Noto Sans NKo',
  'Noto Sans NKo Unjoined',
  'Noto Sans Nabataean',
  'Noto Sans Nag Mundari',
  'Noto Sans Nandinagari',
  'Noto Sans New Tai Lue',
  'Noto Sans Newa',
  'Noto Sans Nushu',
  'Noto Sans Ogham',
  'Noto Sans Ol Chiki',
  'Noto Sans Old Hungarian',
  'Noto Sans Old Italic',
  'Noto Sans Old North Arabian',
  'Noto Sans Old Permic',
  'Noto Sans Old Persian',
  'Noto Sans Old Sogdian',
  'Noto Sans Old South Arabian',
  'Noto Sans Old Turkic',
  'Noto Sans Oriya',
  'Noto Sans Osage',
  'Noto Sans Osmanya',
  'Noto Sans Pahawh Hmong',
  'Noto Sans Palmyrene',
  'Noto Sans Pau Cin Hau',
  'Noto Sans Phags Pa',
  'Noto Sans Phoenician',
  'Noto Sans Psalter Pahlavi',
  'Noto Sans Rejang',
  'Noto Sans Runic',
  'Noto Sans SC',
  'Noto Sans Samaritan',
  'Noto Sans Saurashtra',
  'Noto Sans Sharada',
  'Noto Sans Shavian',
  'Noto Sans Siddham',
  'Noto Sans SignWriting',
  'Noto Sans Sinhala',
  'Noto Sans Sogdian',
  'Noto Sans Sora Sompeng',
  'Noto Sans Soyombo',
  'Noto Sans Sundanese',
  'Noto Sans Syloti Nagri',
  'Noto Sans Symbols',
  'Noto Sans Symbols 2',
  'Noto Sans Syriac',
  'Noto Sans Syriac Eastern',
  'Noto Sans TC',
  'Noto Sans Tagalog',
  'Noto Sans Tagbanwa',
  'Noto Sans Tai Le',
  'Noto Sans Tai Tham',
  'Noto Sans Tai Viet',
  'Noto Sans Takri',
  'Noto Sans Tamil',
  'Noto Sans Tamil Supplement',
  'Noto Sans Tangsa',
  'Noto Sans Telugu',
  'Noto Sans Thaana',
  'Noto Sans Thai',
  'Noto Sans Thai Looped',
  'Noto Sans Tifinagh',
  'Noto Sans Tirhuta',
  'Noto Sans Ugaritic',
  'Noto Sans Vai',
  'Noto Sans Vithkuqi',
  'Noto Sans Wancho',
  'Noto Sans Warang Citi',
  'Noto Sans Yi',
  'Noto Sans Zanabazar Square',
  'Noto Traditional Nushu',
  'Numans',
  'Nunito',
  'Nunito Sans',
  'Nuosu SIL',
  'Onest',
  'Open Sans',
  'Orbit',
  'Orbitron',
  'Orienta',
  'Oswald',
  'Outfit',
  'Overpass',
  'Oxygen',
  'PT Sans',
  'PT Sans Caption',
  'PT Sans Narrow',
  'Padauk',
  'Palanquin',
  'Palanquin Dark',
  'Pathway Extreme',
  'Pathway Gothic One',
  'Pattaya',
  'Pavanam',
  'Paytone One',
  'Philosopher',
  'Play',
  'Plus Jakarta Sans',
  'Pontano Sans',
  'Poppins',
  'Port Lligat Sans',
  'Pragati Narrow',
  'Preahvihear',
  'Prompt',
  'Proza Libre',
  'Public Sans',
  'Puritan',
  'Qahiri',
  'Quantico',
  'Quattrocento Sans',
  'Questrial',
  'Quicksand',
  'REM',
  'Radio Canada',
  'Rajdhani',
  'Raleway',
  'Ramabhadra',
  'Rambla',
  'Rationale',
  'Readex Pro',
  'Recursive',
  'Red Hat Display',
  'Red Hat Text',
  'Reem Kufi',
  'Reem Kufi Fun',
  'Reem Kufi Ink',
  'Rethink Sans',
  'Roboto',
  'Roboto Condensed',
  'Roboto Flex',
  'RocknRoll One',
  'Ropa Sans',
  'Rosario',
  'Rubik',
  'Rubik Mono One',
  'Ruda',
  'Ruluko',
  'Rum Raisin',
  'Russo One',
  'Saira',
  'Saira Condensed',
  'Saira Extra Condensed',
  'Saira Semi Condensed',
  'Sansita',
  'Sarabun',
  'Sarala',
  'Sarpanch',
  'Sawarabi Gothic',
  'Scada',
  'Schibsted Grotesk',
  'Secular One',
  'Sen',
  'Seymour One',
  'Shanti',
  'Share',
  'Share Tech',
  'Shippori Antique',
  'Shippori Antique B1',
  'Siemreap',
  'Signika',
  'Signika Negative',
  'Sintony',
  'Six Caps',
  'Smooch Sans',
  'Snippet',
  'Sofia Sans',
  'Sofia Sans Condensed',
  'Sofia Sans Extra Condensed',
  'Sofia Sans Semi Condensed',
  'Sono',
  'Sora',
  'Source Sans 3',
  'Space Grotesk',
  'Spinnaker',
  'Spline Sans',
  'Stick',
  'Stick No Bills',
  'Strait',
  'Stylish',
  'Sulphur Point',
  'Sunflower',
  'Syncopate',
  'Syne',
  'Tajawal',
  'Tauri',
  'Teko',
  'Telex',
  'Tenali Ramakrishna',
  'Tenor Sans',
  'Text Me One',
  'Thasadith',
  'Timmana',
  'Titillium Web',
  'Tomorrow',
  'Trispace',
  'Truculenta',
  'Tsukimi Rounded',
  'Ubuntu',
  'Ubuntu Condensed',
  'Unbounded',
  'Urbanist',
  'Varela',
  'Varela Round',
  'Varta',
  'Vazirmatn',
  'Viga',
  'Voces',
  'Voltaire',
  'Wendy One',
  'Wire One',
  'Wix Madefor Display',
  'Wix Madefor Text',
  'Work Sans',
  'Yaldevi',
  'Yanone Kaffeesatz',
  'Yantramanav',
  'Ysabeau',
  'Ysabeau Infant',
  'Ysabeau Office',
  'Ysabeau SC',
  'Yusei Magic',
  'ZCOOL KuaiLe',
  'ZCOOL QingKe HuangYou',
  'ZCOOL XiaoWei',
  'Zen Kaku Gothic Antique',
  'Zen Kaku Gothic New',
  'Zen Kurenaido',
  'Zen Maru Gothic',
]
